workflows:
  couplelink-android:
    name: CoupleLink Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      java: 17
    cache:
      cache_paths:
        - ~/.pub-cache
        - build
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Android APK (release)
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

  couplelink-ios:
    name: CoupleLink iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - build
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS (unsigned IPA)
        script: |
          if [ -d "ios" ]; then
            flutter build ios --release --no-codesign
          else
            echo "Skipping iOS build because ios/ folder is missing."
          fi
    artifacts:
      - build/ios/ipa/*.ipa
